apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-failed-app
  labels:
    app: liveness-readiness-test
spec:
  containers:
  - name: main-app
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - containerPort: 9876
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 10
      periodSeconds: 5
      httpGet:
        path: /healthz
        port: 9876
  securityContext:
    runAsUser: 1001
