kind: Service
apiVersion: v1
metadata:
  name: simpleservice
  labels:
    app: simpleservice
spec:
  selector:
    app: main
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9876
    name: http
  type: ClusterIP
